spring:
  redis:
    sentinel:
      master: wemaster
      nodes: 192.168.31.32:26380,192.168.31.41:26380,192.168.31.34:26380
    database: 3
    pool:
      max-active: 100
      max-idle: 50
      min-idle: 20
      max-wait: 5000
    timeout: 5000