server:
  port: 7002

# 指定服务名称
spring:
  application:
    name: eureka-server

# 指定主机地址
eureka:
  instance:
    hostname: eurekaserver2
  client:
    # 指定是否从注册中心获取服务(注册中心不需要开启)
    fetch-registry: false
    # 指定是否将服务注册到注册中心(注册中心不需要开启)
    register-with-eureka: false

    service-url:
      # 注册到另一个Eureka注册中心
      defaultZone: http://eurekaserver1:7001/eureka/,http://eurekaserver3:7003/eureka/
