# 指定运行端口
server:
  port: 8001

# 指定服务名称
spring:
  application:
    name: provider-user

eureka:
  instance:
    instance-id: provider-user-8001
    prefer-ip-address: true
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://eurekaserver1:7001/eureka,http://eurekaserver2:7002/eureka,http://eurekaserver3:7003/eureka