server:
  port: 9001

spring:
  application:
    name: consumer-user

eureka:
  instance:
    prefer-ip-address: true
    # 配置注册中心地址
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

logging:
  level:
    org.sunrain.study.springcloud.demo.HelloFeignService: debug

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      provider-user:
        loggerLevel: full
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true